Add new site
Flameish/Novel-Grabber pull request #210
Opened 2021-06-07 15:28 UTC by posiaden123

2021-06-07 16:47 UTC, Flameish requested changes
I gotta ask, is this like a work in progress because it didn't even work when I tried to test it.

2021-06-07 16:47 UTC, Flameish commented on src/main/java/grabber/sources/librarynovel_com.java
> +import com.sun.javadoc.Doc;
Wrong import

2021-06-07 16:47 UTC, Flameish commented on src/main/java/grabber/sources/librarynovel_com.java
> +
Missing constructor methods:     
public librarynovel_com() {}

public librarynovel_com(Novel novel) {
    this.novel = novel;
}

2021-06-07 16:47 UTC, Flameish commented on src/main/java/grabber/sources/librarynovel_com.java
> +            for (Element chaps : doc.select("div > div > ul > li > a")) {
Not chapter links

2021-06-07 16:47 UTC, Flameish commented on src/main/java/grabber/sources/librarynovel_com.java
> +                metadata.setBufferedCover(cover != null ? cover.attr("abs:data-src") : "");
Missing / Wrong metadata

2021-06-15 20:13 UTC, posiaden123 commented
Yea this was made when I was hella tired, my bad

2021-06-15 20:13 UTC, closed without merging